from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('MotionDriver', src, depend = ['MotionDriver2RTT_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
