from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('MotionDriver', src, depend = ['PKG_USING_MotionDriver'], CPPPATH = CPPPATH)

Return('group')
